### ISSUE TITLE
Make some animations cancelable

### ISSUE THREAD

**Issue by spoenemann** [eclipse-sprotty/sprotty#1]
From theia-ide/sprotty#71:

> Currently we queue all animations. Even though they are short, this can yield to quite a bunch of screenplay when events are fired faster than the resp. animations are running.
> 
> We should investigate how to make at least some animations cancelable. The following animations should then start from the cancelled state instead of the targeted final state of the cancelled animation.

**Comment by spoenemann** [comment]
Example: click on "Scramble all" many times in a row in the Circles example.

**Comment by jbicker** [comment]
I'll take this one.
