### ISSUE TITLE
Incorrect layouting of ports with labels

### ISSUE THREAD

**Issue by tomvdbussche** [eclipse-sprotty/sprotty#165]
When adding a label to a port, the size of that port is changed depending on the label:

![port-size](https://user-images.githubusercontent.com/5674397/65335169-332a6480-dbc4-11e9-8206-e79b1f40b989.png)
with `PortLabelPlacement.INSIDE`:
![port-size-inside](https://user-images.githubusercontent.com/5674397/65335179-3887af00-dbc4-11e9-824c-ba5dac13e2e1.png)

I'm not sure if this is a problem on the server- or client-side. I seems as if the bounds calculation of the port considers the label (since it is a child of the port), while ELK regards these as being indepentent.

To be able to reproduce I've made these changes to the circlegraph example:

`build.gradle`:

```gradle
compile "org.eclipse.elk:org.eclipse.elk.alg.layered:${versions.elk}"
```

`di.config.ts`:

```typescript
configureModelElement(context, 'graph', SGraph, SGraphView);
configureModelElement(context, 'label', SLabel, SLabelView);
configureModelElement(context, 'node', RectangularNode, RectangularNodeView);
configureModelElement(context, 'port', RectangularPort, RectangularNodeView);
configureViewerOptions(context, {
    needsClientLayout: true,
    needsServerLayout: true
});
```

`GraphLayoutEngine.java`:

```java
ElkLayoutEngine.initialize(new LayeredOptions());

configurator.configureByType("graph")
		.setProperty(CoreOptions.ALGORITHM, LayeredOptions.ALGORITHM_ID);
configurator.configureByType("node")
		// .setProperty(CoreOptions.PORT_LABELS_PLACEMENT, PortLabelPlacement.INSIDE)
		.setProperty(CoreOptions.PORT_CONSTRAINTS, PortConstraints.FIXED_ORDER)
		.setProperty(CoreOptions.PORT_ALIGNMENT_DEFAULT, PortAlignment.JUSTIFIED)
		.setProperty(CoreOptions.NODE_SIZE_CONSTRAINTS, SizeConstraint.free());
```

`GraphGenerator.java`:

```java
public SGraph generateGraph() {
	return new SGraph(graph -> {
		graph.setId("graph");
		graph.setChildren(new ArrayList<>());
		graph.getChildren().add(new SNode(node -> {
			node.setChildren(new ArrayList<>(4));
			for (int p = 0; p < 4; p++)
				node.getChildren().add(generatePort(p, "test" + Strings.repeat("_test", p)));
		}));
	});
}

private SPort generatePort(int p, String pLabel) {
	return new SPort(port -> {
		port.setId("port" + p);
		port.setChildren(Collections.singletonList(new SLabel(label -> {
			label.setId("port" + p + "/label");
			label.setText(pLabel);
		})));
	});
}
```

**Comment by spoenemann** [comment]
I moved this to [eclipse/sprotty](https://github.com/eclipse/sprotty) because it's a frontend issue.

We could introduce a special layout (or layout option) to support elements outside of their container's bounds. This does not affect only ports, it could happen with other elements, too.

**Comment by tomvdbussche** [comment]
> I need to provide a proper size for the Ports during "Hidden Render Phase" because the size is also used by the ELK Layout Engine (https://github.com/eclipse/sprotty-layout/) to calculate the edge ends and label positions.

It should be possible to achieve this by creating a view similar to what I mentioned previously:

```typescript
@injectable()
export class SquarePortView implements IView {
    render(port: SPort, context: RenderingContext): VNode {
        return <g>
            <rect class-sprotty-node={port}
                  class-mouseover={port.hoverFeedback} class-selected={port.selected}
                  x="0" y="0" width={Math.max(port.size.width, 0)} height={Math.max(port.size.height, 0)}></rect>
            {context.renderChildren(port)}
        </g>
    }
}
```

And then make the following change in `HiddenBoundsUpdater`:

```typescript
protected getBounds(elm: SVGGraphicsElement, element: BoundsAware): Bounds {
    if (element instanceof SPort) {
        // Extract the rect element containing the port
        const rect = elm.firstChild == null ? undefined : elm.firstChild.firstChild
        return super.getBounds(rect, element)
    }
    
    ...
```

**Comment by rsoika** [comment]
Hi,
can someone provide an example code of the correct implementation of using Ports? I can't find any documentation how Ports should be used.

Also the idea mentioned by @spoenemann to introduce a layout option to support elements outside of their container's bounds sounds very interesting. Is there any place where I can find documentation about all this features?   I already opened an issue #276  regarding this topic. 

Thanks for any help.

**Comment by spoenemann** [comment]
I made a proposal to fix this with an additional attribute in the respective views: #364

@tomvdbussche @BjBe82 @rsoika please have a look whether this is sufficient for your cases.
