### ISSUE TITLE
How to develop diagrams in theia(gitpod)?

### ISSUE THREAD

**Issue by Kreyren** [eclipse-sprotty/sprotty#166]
I'm having hard time deploying sprotty in theia (spent 4 days and i am not even getting closer it feels like) for diagram development can someone help me with it's configuration for this purpose?

Ideally i want the ability to:
1. develop diagrams in real time on gitpod 
2. export diagrams through github pages or a way that updates the website through commit to repository.

Thanks in advance!

**Comment by spoenemann** [comment]
What exactly would you like to achieve? If it's diagrams embedded in a Theia-based application, use [sprotty-theia](https://github.com/eclipse/sprotty-theia) and see [npm-dependency-graph](https://github.com/TypeFox/npm-dependency-graph/tree/master/depgraph-navigator) as an example.
