### ISSUE TITLE
Reimplement `Popup API` as `UIExtension`?

### ISSUE THREAD

**Issue by tortmayr** [eclipse-sprotty/sprotty#236]
When introducing the `UIExtension API` (#63) the question was raised wether we should refactor the Popup stuff to an UI-extension based approach (https://github.com/eclipse/sprotty/pull/63#pullrequestreview-205640214). If we still want to do that we should probably also do it before the 1.0 release.

Requires an analysis of feasibility and consequences of a refactoring.

**Comment by tortmayr** [comment]
From @spoenemann 
>From @spoenemann :
The only issues I’d like to address before a v1.0.0 release are these two:
https://github.com/eclipse-sprotty/sprotty/issues/235
https://github.com/eclipse-sprotty/sprotty/issues/236
>
>My current feeling about these is that we should move these APIs to GLSP because they’re not used by Sprotty itself. But I would like to investigate this in more detail first, and it can happen after v0.14.0.

While I agree with this statement for the `ToolManagerAPI` I'm not sure wether this is also true for the UI extensions.
Even though they are not used by base framework a generic mechanism to extend the diagram (UI) still seems like something that sprotty should support. 
There are also some issues regarding UI extensions (e.g. https://github.com/eclipse-sprotty/sprotty/issues/212) so at least part of the community seems to adopt them.

**Comment by spoenemann** [comment]
Ok the framework comes with the command palette and label editing, both of which are using UIExtension. Let's keep that API.

However, I don't see that as a good fit for popup model contents because those require quite different handling. I propose to close this issue and proceed with preparations for v1.0.0. Ok for you @tortmayr?

**Comment by tortmayr** [comment]
Yes sounds good to me 👍🏼
