### ISSUE TITLE
Online demo and examples

### ISSUE THREAD

**Issue by dumblob** [eclipse-sprotty/sprotty#242]
It seems the demo instance sprotty-demo.typefox.io/ doesn't work any more.

Does anyone have any instance to showcase?

**Comment by spoenemann** [comment]
The easiest way to see the demos is to start a Gitpod workspace:
https://gitpod.io/#https://github.com/eclipse/sprotty/issues/242

Then open the exposed port 8080 in a new browser tab.

**Comment by dumblob** [comment]
Ok. I've never heard of gitpod.

Should there be any other demo instances, just let me know.

**Comment by spoenemann** [comment]
Sprotty's new website includes live demos: https://sprotty.org/

The code is here: https://github.com/eclipse-sprotty/sprotty-website
