### ISSUE TITLE
Moveable ports and live node rescaling

### ISSUE THREAD

**Issue by yuey1203** [eclipse-sprotty/sprotty#268]
Hi, I'm building some additional features was hoping to make sure that I'm not duplicating work or going about it in the right way. 

I want to move the ports but have them remain attached to the parent node on it's edges only. Right now, I am planning on doing this in the frontend by snooping the MoveAction in our modelSource's handle function and readjusting the port's locations to be on the edges of the node. However, I am only doing this when the action is finished. Would there be a better way of doing this that is better suited for Sprotty? 

Another thing that I am trying to do is allow for node resizing in the diagram. I am doing this by adding 4 corner children nodes, snooping on the MoveActions, and when an action is finished, readjusting node sizes if necessary, and doing an updateModel call. Again, any advice on how to generally go able handling these, preferably live (so even when an action is not finished), that would be ideal. In general, I would want to make the diagram feel similar to draw.io when you can dynamically resize and move elements. 

Another thing would be for rerouting of edges, but that seems to be a whole other can of worms. Is there anything sprotty specific that can do live rerouting? We're currently handling rerouting on the backend with a slower libavoid process, but was wondering if there was anything built-in that would help with that. Thanks!

**Comment by spoenemann** [comment]
At least the resizing should be covered with [GLSP](https://www.eclipse.org/glsp/), maybe even other requirements of yours.

Fully automatic routing of edges without repositioning the nodes is difficult. I'm not aware of any library for that other than libavoid.
