### ISSUE TITLE
What's the different between ManhattanRectangularAnchor, ManhattanEllipticAnchor, ManhattanDiamondAnchor

### ISSUE THREAD

**Issue by rsoika** [eclipse-sprotty/sprotty#281]
I want to implement in my BPMN project an improved version of Manhattan routing. One issue is computing the anchor point for an edge depending on the element type. 
As far as I understand the `IAnchorComputer` is responsible to compute this point in the diagram. 

In the sprotty implementation there are three additional AnchorComputer for manhanttan routing:  `ManhattanRectangularAnchor, ManhattanEllipticAnchor, ManhattanDiamondAnchor`

Can you briefly explain what they are good for? 

Can you show a short example how to register a custom implementation of an IAnchorComputer? Because I currently do not understand which of the three Manhattan Anchors the ManhattanEdgeRouter.KIND (which I am using) is choosing.

Sorry for asking such stupid questions. Unfortunately the implementations are not commented :-(

**Comment by spoenemann** [comment]
They are for computing anchor points of edges on the border of source / target nodes, specifically for the Manhattan router which uses orthogonal bend points. The anchor computation depends on the shape of the nodes, hence there are three different ones. The registration happens in `AnchorComputerRegistry` with the scheme `{router_kind}:{anchor_kind}`, for example `manhattan:rectangular`.

**Comment by rsoika** [comment]
Thanks for your answer. Do you mean that I can implement additional AnchorComputers in my project, and simply register them via the AnchorComputerRegistry in my own di.config.ts? Something like:

    bind(TYPES.IAnchorComputer).to(BPMNNodeAnchor).inSingletonScope();

And my own implementation would simply do something like:

````java
@injectable()
export class BPMNNodeAnchor implements IAnchorComputer {

    static KIND = ManhattanEdgeRouter.KIND + ':' + BPMN_ANCHOR_KIND;

    get kind() {
        return ManhattanRectangularAnchor.KIND;
    }

    getAnchor(connectable: SConnectableElement, refPoint: Point, offset: number): Point {
        // compute anchor point depending on the BPMN Element type 
        ........

        return point;
    }
}
````

But how and where would I specify which AnchorComputer should be used by my own ElementNodes? How does the ManhattenRouter, which I am currently using, know that my BPMN-Nodes should use my BPMNNodeAnchor?

On the other hand I now guess that for example the ManhattanDiamondAnchor could be used for a BPMN gateway: 

![image](https://user-images.githubusercontent.com/1339124/160482430-d106d70c-c0d3-4b04-998a-67af85c04c4f.png)

...even if I need to ajust it a in some way....?

**Comment by spoenemann** [comment]
The model elements have an optional `anchorKind` property:
https://github.com/eclipse/sprotty/blob/master/packages/sprotty/src/lib/model.ts

You could create your own subclasses of SNode.

**Comment by rsoika** [comment]
OK - now I got it! Thanks a lot. 
I will try to write a short tutorial for my own project and share it with you.

**Comment by rsoika** [comment]
I have written a short tutorial how to work with AnchorComputers and Ports:

https://github.com/imixs/open-bpmn/blob/master/doc/SPROTTY_ANCHORS_AND_PORTS.md

The Port part is based on GLSP, so maybe you can't  use it in that way? 

But any way, if you like it you can take over the document into your WIKI. I will not continuing documenting this in that way as I need to document the specific adaption of the AnchorComputer concept in my own BPMN project.

**Comment by rsoika** [comment]
@spoenemann  Can you please help me once again. I still did not find a correct way to compute the anchor points and the routing for my BPMN elements.

The main problem is that my Event and Gateway elements have a label below the circle or diamond. So the target bounds for the part to connect to (the diamond or circle) are smaller than the bounds for the complete element including the label below.

![image](https://user-images.githubusercontent.com/1339124/161319268-3008c873-dbe5-49c9-a132-aa5294adad4a.png)

I already implemented custom BPMN Task and BPMN Event AnchorComputers. For the Task element this was quite simple by computing the centre position of the border. 
For the Event Element it was more complex. But I solved this by simply re-computing a custom bounds object by taking the bounds of the inner circle and not the complete element which has larger dimensions because of the label below:

![image](https://user-images.githubusercontent.com/1339124/161318635-7a1e82cd-af84-42a4-be86-afc569c04ec5.png)


````java
@injectable()
export class BPMNPolylineEventAnchor implements IAnchorComputer {
    ....
    getAnchor(connectable: SConnectableElement, refPoint: Point, offset: number): Point {
	const b = connectable.bounds;
        console.log(' .... BPMNPolylineEventAnchor....');
		const bounds = {
                        // radius of the circle is 20
			x: b.x - 20,
			y: b.y - 20,
			width: 40,
			height: 40
		};
....
}
````

This worked well at the first view. But than I  it noticed that the `ManhattanEdgeRouter` had a problem to compute the route correctly.

![image](https://user-images.githubusercontent.com/1339124/161318883-bcd6aad2-5fe9-4bb3-afa0-37a8dd5e46a9.png)

And this seems to be because the `ManhattanEdgeRouter` also need the bounds of the target/source element to compute the best route. I already tried to overwrite the 'get bounds' in my EventNode model element but this did not solve the problem (the element now jumps around in the diagram panel).

So I looks that I have to reimplement a custom `ManhattanEdgeRouter` too and re-compute the correct bounds depending on the type of my target element.

Have you any idea to solve this kind of problem more elegant? 
Core problem: An Element node has a smaller Bounds area for routing than the outer bounds of the complete element are.
It would be ideal if the router would ask my ElementNode if it has a `boundsHint` .....?

**Comment by rsoika** [comment]
Ok, sorry for asking stupid questions. I found the solution by myself. I simply have to define a port with the same dimensions as my cycle. It's the solution I have described in my own [docu](https://github.com/imixs/open-bpmn/blob/master/doc/SPROTTY_ANCHORS_AND_PORTS.md).

**Comment by rsoika** [comment]
Finally I solved all problems and updated my documentation. You can take it if you like:
https://github.com/imixs/open-bpmn/blob/master/doc/SPROTTY_ANCHORS_AND_PORTS.md

**Comment by spoenemann** [comment]
Thanks! Let's keep this open so we can find the content when we revisit the documentation. It would be great to have a dedicated website for Sprotty that hosts the documentation, and to start writing more of it.

**Comment by rsoika** [comment]
@spoenemann  I was now able to update my GLSP project to the latest version which is now based on sprotty version [0.11.0-next.e898c14.30](https://www.npmjs.com/package/sprotty/v/0.11.0-next.e898c14.30). 

And I can give you the feedback, that the Manhattan routing seems now working much better as in version 0.10. 
Can I expect a new behaviour also in version 0.11.1 ?

**Comment by tortmayr** [comment]
@rsoika There seems to be an issue with the version numbers of sprotty's next versions. `0.11.0-next.e898c14.30` is reflecting the current master and should actually be labeled `0.12.0-next.e898c14.30 `.  So you are already consuming a version that is newer than the 0.11.1 release.
