### ISSUE TITLE
ELK: moving a node and recalculating the edge bends

### ISSUE THREAD

**Issue by wagnerpaz** [eclipse-sprotty/sprotty#286]
hey.. I've heard that you guys were able to implement ELK node fixed position (instead of having ELK calculate the node position and having it just calculating the edges). I saw an example where you were able to drag a node freely and the edges updates correctly. How can I use this feature? I want to implement a diagram with layered algorithm.

**Comment by spoenemann** [comment]
We have Manhattan-style (orthogonal) edge routing that auto-updates itself when nodes are moved, see the class diagram example in this repo. What that built-in routing does not do is avoiding overlaps with other nodes. If you want that, you need to integrate something like [libavoid](https://www.adaptagrams.org/documentation/libavoid.html).

@planger is there a public component to use libavoid with Sprotty? I remember you mentioned that some time ago.

**Comment by spoenemann** [comment]
> I want to implement a diagram with layered algorithm.

The layer-based algorithm of ELK is not able to route edges with fixed node positions. There have been attempts to reimplement the libavoid algorithm in ELK, but so far there's nothing usable yet.

**Comment by planger** [comment]
> We have Manhattan-style (orthogonal) edge routing that auto-updates itself when nodes are moved, see the class diagram example in this repo. What that built-in routing does not do is avoiding overlaps with other nodes. If you want that, you need to integrate something like [libavoid](https://www.adaptagrams.org/documentation/libavoid.html).
> 
> @planger is there a public component to use libavoid with Sprotty? I remember you mentioned that some time ago.

Here is a rather up-to-date description of the state: https://github.com/mjwybrow/adaptagrams/issues/44#issuecomment-1105665758

As far as I know it works at least for a demo and is consumable. But I haven't checked in detail for a while. @Aksem what do you think? Also, wouldn't it be best have the Sprotty integration of libavoid as part of Sprotty? If necessary, also the libavoid-js to have it in the Eclipse Foundation?

**Comment by Aksem** [comment]
Update: [sprotty-routing-libavoid](https://github.com/Aksem/sprotty-routing-libavoid) v1.0.35 released. Performance was improved, and the demo works well with ~60+ nodes.
Also, there is the first real-world usage: it was integrated into [bigER modeling tool](https://github.com/borkdominik/bigER) (note: the new version was not published in the marketplace yet and should be built from sources). Documentation of `sprotty-routing-libavoid` is still missing, it will be the next step.

**Comment by spoenemann** [comment]
In case someone wants edge routing as an explicit action (not automatically triggered), we now have it integrated with ELK, so it can be used with the existing sprotty-elk adapter:

https://www.eclipse.org/elk/blog/posts/2022/22-11-17-libavoid.html
