### ISSUE TITLE
Consider using `peerDepdencies` for inversify

### ISSUE THREAD

**Issue by tortmayr** [eclipse-sprotty/sprotty#296]
see https://github.com/eclipse/sprotty/pull/292#issuecomment-1137159348

**Comment by spoenemann** [comment]
Done with #357

**Comment by spoenemann** [comment]
We decided to revert the change because it is problematic in some circumstances, see https://github.com/eclipse-sprotty/sprotty/pull/429#discussion_r1492091716.

@tortmayr feel free to reopen this issue if you want to continue the discussion.
