### ISSUE TITLE
Selected elements get lost when using scroll bars

### ISSUE THREAD

**Issue by aurelio-pennacchio** [eclipse-sprotty/sprotty#302]
I activated the GLSPProjectionView in the di-config.ts file using the following line of code
`configureModelElement(context, DefaultTypes.GRAPH, GLSPGraph, GLSPProjectionView);`
Now when I have an active selection of a node of the GGraph and then I use the scrollBars I lose the selection while I was expecting to mantain the previously selected elements.
Is it a configuration issue from my side or something else?

Thank you for all your work!

**Comment by dhuebner** [comment]
@aurelio-pennacchio 
Thank you for reporting! I noticed that as well, it's really a bit annoying.
> Is it a configuration issue from my side or something else?

It is not a configuration issue. From what I see in the codebase  it is _expected_ behavior. Viewport scroll bar elements are not a part of the sprotty root model, hence when clicking on them, Selection Listener handles selection on the next registered parent element (sprotty root).
We should fix this.

Possible solutions could be:
- block propagation of mouse click events in viewport elements
- distinguish between mouseDown and mouse start dragging (don't deselect on mouse start drag)
- let SelectMouseListener be aware of viewport components and handle respectively
- in addition it would be nice to use `scroll wheel + Ctrl (or Alt) ` to scroll and not Zoom

**Comment by dhuebner** [comment]
Fixed in master
