### ISSUE TITLE
is there a way that LangiumDiagramGenerator class can enable more features (hover, popup, etc) like ModelSource class?

### ISSUE THREAD

**Issue by LockedAwya** [eclipse-sprotty/sprotty#350]
Hi, I am trying to build a DSL with langium and using langium-sprotty library to generate a graphical model. However, it seems that this library does not support such features.

I wonder if there is a way to combine these two classes, or I have to take one over another?

Thanks in advance.

**Comment by spoenemann** [comment]
Hover popup content requests need to be processed by the DiagramServer, which is created in [default-module.ts](https://github.com/langium/langium/blob/main/packages/langium-sprotty/src/default-module.ts). The default is the `DiagramServer` class from the `sprotty-protocol` package, but you can customize the factory to create your own subclass.

That said, I agree that the `langium-sprotty` integration should offer more default functionality, including some sensible behavior for hover popups. We just haven't got to it yet, but contributions are welcome.
