### ISSUE TITLE
Bad dev experience with edge selection and routing

### ISSUE THREAD

**Issue by spoenemann** [eclipse-sprotty/sprotty#368]
Edges are selectable by default. And the default behavior when selecting an edge is to enable its editing mode, which makes explicit routing handles visible. But these are only visible if the respective element types are registered like this:
```typescript
        configureModelElement(context, 'routing-point', SRoutingHandleImpl, SRoutingHandleView);
        configureModelElement(context, 'volatile-routing-point', SRoutingHandleImpl, SRoutingHandleView);
        configureModelElement(context, 'bezier-create-routing-point', SRoutingHandleImpl, SBezierCreateHandleView);
        configureModelElement(context, 'bezier-remove-routing-point', SRoutingHandleImpl, SBezierCreateHandleView);
        configureModelElement(context, 'bezier-routing-point', SRoutingHandleImpl, SBezierControlHandleView);
```

Otherwise strange overlapping messages are shown in the diagram:
<img width="308" alt="Screenshot 2023-07-17 at 13 54 43" src="https://github.com/eclipse-sprotty/sprotty/assets/4067210/23c60696-9b3a-4a7a-bfa3-d18b52c8765d">

We should find a way to improve the developer experience in this regard.

**Comment by jonah-iden** [comment]
This really irritated me alot when i first started with sprotty. I'll see if i can find a solution. Could someone assign me?
