### ISSUE TITLE
sprotty-vscode tranform confused

### ISSUE THREAD

**Issue by zrwsmd** [eclipse-sprotty/sprotty#377]
the demo example https://github.com/eclipse-sprotty/sprotty-vscode have MrsGrantsSecretCompartment.sm,i am a little confused  how this file generated from corresponding diagram,that is to say how should right part  tranform to left part ,i did not see any code related to it since my requirement is #375
![image](https://github.com/eclipse-sprotty/sprotty/assets/26995040/6df9696a-3d9e-49e9-ba2c-f307f019aedf)

**Comment by spoenemann** [comment]
It's the other way around: the right part (diagram) is generated from the left part (DSL text). The code for this transformation is here:
https://github.com/eclipse-sprotty/sprotty-vscode/blob/master/examples/states-langium/language-server/src/diagram-generator.ts

**Comment by zrwsmd** [comment]
so if i need to achieve my requirement #375  ,to tranform industrial Programming Language LD(Ladder Diagram) to other specific lauguage like C++ or PLC ST (Structured Text）language,LD is similar to right part,C++ or PLC ST (Structured Text）language is similar to left part,i am considering define  .langium extesion file to generate left part code template ,or do i have to write left part code by myself

**Comment by spoenemann** [comment]
Langium can be used to create a parser and a language server for your ST language. Serializing text from another format is also on the roadmap, but currently not supported. So you need to generate the text with normal JavaScript / TypeScript templates.

**Comment by zrwsmd** [comment]
can not clealy catch your meaning ,is my requirements currently can not achieved by sprotty and langium?

**Comment by zrwsmd** [comment]
> Langium can be used to create a parser and a language server for your ST language. Serializing text from another format is also on the roadmap, but currently not supported. So you need to generate the text with normal JavaScript / TypeScript templates.

can not clealy catch your meaning ,what do you mean by "",is my requirements currently can not  be achieved by sprotty and langium?
i am thinking use langium as language server,VS Code extensions as language client,vscode webview to render LD diagram,which receive VS Code extensions response,the response from language server via lsp protocol

**Comment by spoenemann** [comment]
Yes you can use Sprotty and Langium for those things. The only step that is currently not done automatically is to generate ST text from a diagram, you would need to implement that yourself. Langium has nice APIs to generate text: https://www.typefox.io/blog/code-generation-for-langium-based-dsls

**Comment by zrwsmd** [comment]
> Yes you can use Sprotty and Langium for those things. The only step that is currently not done automatically is to generate ST text from a diagram, you would need to implement that yourself. Langium has nice APIs to generate text: https://www.typefox.io/blog/code-generation-for-langium-based-dsls

.i have seen laugium example like domainmodel or statemachine,take domainmodel as an example ,it firstly define a custom language with extension  .domainmodel,then generate ast code by langium-cli,then use cli to generate java code with the help of generated ast code ,so if i need to achieve this requirement,i am thinking define a custom lauguage like extension .aaa,i write 
aaa.langium grammar,then generate ast code,then i write example.aaa ,corresponding diagram is generated  by extends LangiumDiagramGenerator,then i use cli to generate ST code by using generated ast code,is my idea correct?

**Comment by zrwsmd** [comment]
the requirement is when right part changed,corresponding left part code is changed too,
![image](https://github.com/eclipse-sprotty/sprotty/assets/26995040/bbe050bd-a83a-4ca4-ab5f-6bdbec69cde9)
also,righr part is operated by user on diagram editor,like drage a component or add a component
i was wondering whether sprotty-langium  can achieve this requirement ,or should i use glsp instead

**Comment by spoenemann** [comment]
LD is a graphical language. What format are you using to persist it? If it's a custom text language, you can use Langium to parse that and then generate other formats like ST or C++. But if you use XML or JSON, you don't need Langium; just use plain TypeScript or some template library in that case.

**Comment by zrwsmd** [comment]
when right part delete a component for example,i found corresponding  left part  also changed too,how their synchronized，i did not found related code
![image](https://github.com/eclipse-sprotty/sprotty/assets/26995040/5fbae3a2-ee9d-4030-946e-bb80bf1ae75c)

**Comment by spoenemann** [comment]
The code is here: https://github.com/eclipse-sprotty/sprotty-vscode/blob/master/packages/sprotty-vscode-webview/src/lsp/editing/delete-with-workspace-edit.ts
