### ISSUE TITLE
Reconsider generic definiton of `RequestAction`

### ISSUE THREAD

**Issue by tortmayr** [eclipse-sprotty/sprotty#378]
Currently the `RequestAction` interface has to be defined with a generic type for its `ResponseAction`.
However, this generic parameter is not used anywhere:
![response](https://github.com/eclipse-sprotty/sprotty/assets/2311075/d24d100a-bd6a-4261-970d-41178a55755f)

This means the compiler cannot implicitly derive the corresponding `ResponseAction` type and the entire
generic definition is effectively useless.

I guess the Idea behind this was to enable typed retrieval of response when using `ActionDispatcher.request`.
However, this does not work as expected because the compiler cannot infer the correct ResponseAction type:
![image](https://github.com/eclipse-sprotty/sprotty/assets/2311075/cc7a0355-fbee-4254-a231-be9a5cc02292)

So in its current form generic RequestActions don`t make any sense and we should probably remove them and change
`ActionDispatcher.request` to 
```ts
    request<Res extends ResponseAction>(action: RequestAction): Promise<Res> 
```

An alternative, hacky approach that would also work is adding an optional property to the RequestAction to ensure that the generic type is used.
```ts
export interface RequestAction<Res extends ResponseAction> extends Action {
    requestId: string
    __responseType?:Res
}
```

Then the compiler can implicitly derive the correct repsonse type.
(I tried this out in [TS playground](https://www.typescriptlang.org/play?ssl=5&ssc=1&pln=6&pc=1#code/FASwdgLgpgTgZgQwMZQAQCUoEcCuUDOEAgkhCAPZgA8m+ADpfmlAB7RgAm+GBDYTJMpQB8Ab2CpUAa3AcAXIRjgA5gBoJqGNjyEAkvMUqNAfWNb6jKABUAnnSgB+ObT5NgAX2ChIsRCh4W-FCCFGDikjKcChBKYGoa5q5Q+tGx8Z7e0PDIaJi4BBAAsuQcUAA2IZSorOxcPPmEldQAylBFJeVNYhpw5OSpRhngWX5ore2lFaSh1WxQnNwulk3hqABGCDADcR5ecDhg01VaDRA0vJaztYsXQV0AFCc6xEdgztoFTeeBTMIAlO8flBVloIDgYGBUKJ3KgENwEGAbLsvF4kIwIJoPo1Xu9TsVJk0ALyiSLyABEZNUTwKKQpql6-QpnjR-AxiUshMxp0eWJeQjAf2AAHohZJJAA9BzAFmETFAgCMnOphCo43xnVewh5pyagpFYtQkul6LlSQATEreVQSbI5GT8OQALZQSmmyy09lBMnuLXKvmhPWisVG4BAA)

@spoenemann WDYT? How should we handle this?

**Comment by spoenemann** [comment]
AFAICT, there is no problem with the generic parameter not being used, but rather a limitation with TypeScript's type system:
```typescript
const res = await this.actionDispatcher.request(GetSelectionAction.create());
// res is inferred to ResponseAction
```

This is because of the indirection in the definition of the action type:
```typescript
interface GetSelectionAction extends RequestAction<SelectionResult> { }
```
This is something that actually works better with Java, where the type system can correctly derive the method's type parameter.

But it works correctly if I write it like this:
```typescript
const requestAction: RequestAction<SelectionResult> = GetSelectionAction.create();
const res = await this.actionDispatcher.request(requestAction);
// res is inferred to SelectionResult
```

It also works to change the return type of `GetSelectionAction.create()` to `RequestAction<SelectionResult>` instead of `GetSelectionAction`. But that might not always be desirable. Possible solution: add another function `GetSelectionAction.createRequest()` returning `RequestAction<SelectionResult>`.

**Comment by tortmayr** [comment]
Explicitly typing the requestAction to `RequestAction<SelectionResult>` seems to do the trick. Nevertheless there is still an issue if we explicitly set the type in the `request` function
```ts
export interface TestResponse extends ResponseAction{
   kind:"test"
   foo:string
}

const getSelectRequest: RequestAction<SelectionResult> = GetSelectionAction.create();
const res2 = await actionDispatcher.request<TestResponse>(getSelectRequest); // Compiler should complain here, but does not
  //    ^?const res2: TestResponse

```
This should result in a compile error, but does not. A stricter method signature of  `actionDispatcher.request` 
would also cover this case, but this also seems undesirable to me
```ts
 request<Res extends ResponseAction, Req extends RequestAction<Res>(action: Req): Promise<Res>
```

>AFAICT, there is no problem with the generic parameter not being used, but rather a limitation with TypeScript's type system:

Yes you are partly right. It's a limitation of the typescript system that only occurs when the generic literal is unused. As soon as I add any property to the `RequestInterface´ that uses the `Res` literal everything works as expected out of the box

```ts
export interface RequestAction<Res extends ResponseAction> extends Action {
    requestId: string
    __requestType?:Res
}

//
const res = await actionDispatcher.request(GetSelectionAction.create());
  //    ^? const rest: SelectionResult

const res2 = await actionDispatcher.request<TestResponse>(GetSelectionAction.create()); // Compilation error because GetSelectionAction is not assignable to ReqestAction<TestResponse>
```

>Possible solution: add another function GetSelectionAction.createRequest() returning RequestAction<SelectionResult>

That would definitely be helpful, but also somewhat unexpected. Having to use an extra creation method to support correct typechecking is a bit weird to me.

**Comment by spoenemann** [comment]
I think it's ok to add a property to the interface, Microsoft has done the same in their JSON-RPC implementation:

https://github.com/microsoft/vscode-languageserver-node/blob/dfdb85d46f212e20de9df17074e84b97c4e7f95e/jsonrpc/src/common/messages.ts#L254-L262

I'm ok with that solution. Do you want to create a PR?
