### ISSUE TITLE
generator-sprotty is not part of the sprotty organization

### ISSUE THREAD

**Issue by tortmayr** [eclipse-sprotty/sprotty#386]
There seems to be an issue with the newly introduced `generator-sprotty` package.
Only next versions are available on npm `https://www.npmjs.com/package/generator-sprotty?activeTab=versions`.
To me it looks like this package got published under the ownership of `eclipse-sprotty-bot` and is therefore not part of the sprotty npm organization. I guess this happened because npm can not derive the corresponding organization of unscoped packages .

We should probably trigger the Eclipse IT team so that they transfer the package ownership to the sprotty org.

**Comment by tortmayr** [comment]
@spoenemann

**Comment by spoenemann** [comment]
I moved this to the Help Desk: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3765
