### ISSUE TITLE
Remove `SModelExtension` interface

### ISSUE THREAD

**Issue by tortmayr** [eclipse-sprotty/sprotty#387]
The `SModelExtension` interface in its current form serves no purpose.
I guess the original idea was to use this as marker interface for all model feature extensions.
However, the concept of empty marker interfaces is something that works well in other strongly-typed languages e.g. Java but
does not translate to typescript.
Since you cannot use an instanceof check for interfaces (and a typeguard for an empty interface is also not an option)
the interface effectively has no purpose. We should probably just remove it before the 1.0.0 release.
@spoenemann wdyt?

**Comment by spoenemann** [comment]
Yes, we can write notes in the documentation of the respective interfaces instead.

Feel free to create a PR if you have time. I am quite packed in this and next week.
