### ISSUE TITLE
Remove test-helper and jsdom dependency

### ISSUE THREAD

**Issue by spoenemann** [eclipse-sprotty/sprotty#390]
The jsdom library has a license issue:
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10784#note_1241810

We use it only in test-helper.ts, but AFAICT we don't use that anywhere. We should consider to deprecate it so we can remove the dependency in v2.0.0.

**Comment by gfontorbe** [comment]
I can take care of that

**Comment by spoenemann** [comment]
Actually we could even publish this in a v1.0.1 release because test-helper is not included in the published library.

**Comment by spoenemann** [comment]
Fixed with #399.
