### ISSUE TITLE
Fix versions of Sprotty dependencies

### ISSUE THREAD

**Issue by glatuske** [eclipse-sprotty/sprotty#418]
When using Sprotty as part of a prototype we had issues with latest snabbdom release.
Because Sprotty just requires anything equal or larger than 3.5.1 ("snabbdom": "^3.5.1") the latest release has been resolved.

The new version of snabbdom is build on ECMA Script module system and requires updates on our side.
Please fix the version of dependencies to a concrete version or at least to just allow bug fixes only.

**Comment by spoenemann** [comment]
The fix is now also available in [v1.1.1](https://github.com/eclipse-sprotty/sprotty/releases/tag/v1.1.1)
