### ISSUE TITLE
Enhance Sprotty JSX/TSX support

### ISSUE THREAD

**Issue by glatuske** [eclipse-sprotty/sprotty#419]
Sprotty uses JSX/TSX for the graph views. Building components as described in React documentation (https://react.dev/learn/passing-props-to-a-component) is not possible due to normalization of attributes (normalizeAttrs). Also some SVG attributes cannot be passed as expected (e.g. attrs-font-size instead of font-size)

Current:
`@injectable()
export class NodeView extends ShapeView {

	render(node: Readonly<SNodeImpl & CustomNode>, context: RenderingContext): VNode | undefined {
		return <g >
			{Tooltip({ type: node.type })}
			{Rectangle({ size: node.size, fill: node.fillColor })}
                        <text class-sprotty-label={true} attrs-font-size="7">{label.text}</text>
			{context.renderChildren(node)}
		</g>;
	}
}`

Expected:
`@injectable()
export class NodeView extends ShapeView {

	render(node: Readonly<SNodeImpl & CustomNode>, context: RenderingContext): VNode | undefined {
		return <g >
			<Tooltip type={node.type} />
			<Rectangle size={size: node.size} fill={node.fillColor} />
                        <text class-sprotty-label={true} font-size="7">{label.text}</text>
			{context.renderChildren(node)}
		</g>;
	}
}`

**Comment by tortmayr** [comment]
Potential related issue: https://github.com/eclipse-sprotty/sprotty/issues/178

**Comment by jbicker** [comment]
I will take care of this one.
