### ISSUE TITLE
Self-contained SVG Export

### ISSUE THREAD

**Issue by glatuske** [eclipse-sprotty/sprotty#421]
The usage of Sprotty in our project requires to create static SVG screenshots from the graphs rendered with Sprotty. As an additional requirement this needs to be done headless (with node.js only?) and fully self-contained SVGs (on CSS referenced or inlined - all styles need to be part of the corresponding SVG elements).

**Comment by jbicker** [comment]
@spoenemann, I'll take care of this one.

**Comment by glatuske** [comment]
@spoenemann We would need a fully calculated size of the exported SVG having width and height set. viewBox and other attributes are not required.

**Comment by glatuske** [comment]
@spoenemann Please analyse the need to render the hidden model again in case of SVG export. In general an analysis of the performance would be good. Where is time spent on SVG export compared to normal rendering (e.g. embedding CSS styles, size calculation, ...)
