### ISSUE TITLE
ELK rectpacking causes error

### ISSUE THREAD

**Issue by Drakae** [eclipse-sprotty/sprotty#422]
I want to use the rectpacking layout algorithm of ELK (using Sprotty version 0.13.0). However, when setting the property in the layout config I get the following error:
Failed to generate diagram: Error: org.eclipse.elk.core.UnsupportedConfigurationException: Layout algorithm 'rectpacking' not found

I tested the JSON of my graph in elklive as well as with an ELK CLI (both times the versions 0.8.2 and 0.9.0) and there it works just fine.
Example JSON:
```
{
    "id": "root",
    "layoutOptions": {
        "org.eclipse.elk.algorithm": "rectpacking"
    },
    "children": [
        {
            "id": "dummy",
            "children": [],
            "edges": [],
            "labels": [
                {
                    "id": "dummyLabel1_label",
                    "text": "dummy",
                    "x": 5,
                    "y": 5,
                    "width": 43.1181640625,
                    "height": 15
                }
            ],
            "ports": [],
            "width": 53.1181640625,
            "height": 25
        },
        {
            "id": "dummy2",
            "children": [],
            "edges": [],
            "labels": [
                {
                    "id": "dummyLabel2_label",
                    "text": "dummy",
                    "x": 5,
                    "y": 5,
                    "width": 43.1181640625,
                    "height": 15
                }
            ],
            "ports": [],
            "width": 53.1181640625,
            "height": 25
        }
    ],
    "edges": []
}
```

**Comment by spoenemann** [comment]
How are you integrating ELK with Sprotty – elkjs, elk-server, sprotty-server, or something else?

**Comment by Drakae** [comment]
I use sprotty-elk and elkjs.

**Comment by spoenemann** [comment]
Ok then this issue should rather be discussed in the [elkjs repo](https://github.com/kieler/elkjs).

Just one hint: are you using the latest version of elkjs, and have you [enabled the rectpacking algorithm in the API](https://www.npmjs.com/package/elkjs#api)?

**Comment by Drakae** [comment]
Thanks for the hint, I overlooked this.
