### ISSUE TITLE
sprotty-elk sometimes doesn't delete old edge bends on layout changes

### ISSUE THREAD

**Issue by semira222** [eclipse-sprotty/sprotty#427]
The video shows the issue. When expanding/collapsing nodes, edge bends are not deleted from the layout, which can turn into quite the spaghetti on larger graphs. This only happens when the edge wouldn't need bends in the new layout. If the new edge layout just needs different bend points the old bend points are being deleted as expected.

https://github.com/eclipse-sprotty/sprotty/assets/77962181/a68bfd13-770a-4174-ae82-829d570015cb

**Comment by spoenemann** [comment]
We haven't seen this in other applications using the collapse / expand feature. I think solving the issue is not possible without seeing the source code of your implementation.

**Comment by semira222** [comment]
I am using elk for layouting, probably should have made that clearer. I managed to reproduce the bug in the randomgraph example from the sprotty repo by reducing the number of nodes and edges to 5 each:

https://github.com/eclipse-sprotty/sprotty/assets/77962181/5d5a1620-328a-41d7-8376-fde214ece0a3

**Comment by jbicker** [comment]
@spoenemann, I can have a look a it.

**Comment by spoenemann** [comment]
It turned out this is an ELK bug: https://github.com/eclipse/elk/issues/1001
