### ISSUE TITLE
How to extend the Manhattan Router?

### ISSUE THREAD

**Issue by rsoika** [eclipse-sprotty/sprotty#474]
Hi, I plan to extend the routing algorithm of the Manhattan router. Can you give me a short help how to get started with such a topic?
I guess I need to overwrite/extend some class with at the end defining a custom router.kind -right?

My project [open-bpmn](https://www.open-bpmn.org) is based on GLSP and maybe I should ask the same question there? I am not sure how the relationship between these two projects is now.

**Comment by tortmayr** [comment]
Hi @rsoika,
lets discuss this in the GLSP project (https://github.com/eclipse-glsp/glsp/discussions/1435)
